# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Build.SourceBranchName).$(rev:r)

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-commercial/fpi/*
    - modules12/*
    - powershell/fpi/*

pool:
  name: LinuxBuildDevelopmentPool

steps:
- template: ${{variables['System.DefaultWorkingDirectory']}}/yaml-templates/Step/standard-infra-build.yml
  parameters:
    terraform_project_folder_name: 'fpi'
    service_connection: 'dev-core'
    development_variables_file: 'variables_development.tfvars'
    terraform_command: 'terraform'