# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Build.SourceBranchName).$(rev:r)

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-commercial/bmp/*
    - modules/*

pool:
  name: LinuxBuildDevelopmentPool

variables:
  terraform-project-folder-name: 'bmp'

steps:
- template: ${{variables['System.DefaultWorkingDirectory']}}/yaml-templates/Step/standard-infra-build.yml
  parameters:
    terraform_project_folder_name: 'bmp'
    service_connection: 'dev-core'
    development_variables_file: 'variables_development.tfvars'
    terraform_command: 'terraform'
    