name: $(Build.DefinitionName)_$(Build.SourceBranchName).$(rev:r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - azure-commercial/ignite/*

pool:
  name: DevelopmentPrivatePoolwin2016

variables:
  terraform_project_folder_name: 'azure-commercial/ignite'


steps:
- template: ${{variables['System.DefaultWorkingDirectory']}}/yaml-templates/Step/publish-artifact.yml
  
    
