parameters:
- name: environment
  type: string
  default: ''
- name: environment_acronym
  type: string
  default: ''
- name: terraform_project_folder_name
  type: string
  default: ''
- name: agent_pool
  type: string
  default: ''
- name: service_connection
  type: string
  default: ''

jobs:
- deployment: 'Apply_${{upper(parameters.environment_acronym)}}'
  displayName: '${{upper(parameters.environment_acronym)}} Apply'
  pool:
    name: ${{parameters.agent_pool}}
  workspace:
    clean: all
  dependsOn: []
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ${{variables['System.DefaultWorkingDirectory']}}/${{parameters.terraform_project_folder_name}}/coupa/project-tf-coupa-apply-steps.yml
          parameters:
            environment_acronym: ${{parameters.environment_acronym}}
            service_connection: ${{parameters.service_connection}}